config/routes.rb
Rails.application.routes.draw do
  get 'tops/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  post 'guest_sign_in', to: 'application#guest_sign_in'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get 'follows'
      get 'followers'
      get 'like'
    end
  end
  namespace :admin do
    resources :users
  end

  resources :tops, only: [:index]
  root 'tops#index'
  post '/tops/guest_sign_in', to: 'application#guest_sign_in'
  post 'guest_admin_sign_in', to: 'application#guest_admin_sign_in'

  resources :relationships, only: [:create, :destroy]

  resources :labels

  resources :sakes do
    resources :comments
  end
  
  get 'search', to: 'sakes#search'

  resources :favorites, only: [:index, :create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :sake
  belongs_to :user

  validates :reply, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_sake

  def create
    @sake = Sake.find(params[:sake_id])
    @comment = @sake.comments.build(comment_params)
    @comment.user_id = current_user.id
  
    if @comment.save
      redirect_to sake_path(@sake)
    else
      flash[:alert] = @comment.errors.full_messages.to_sentence
      redirect_to sake_path(@sake) # この行を追加してください。
    end
  end

  def destroy
    @comment = @sake.comments.find(params[:id])

    if current_user == @comment.user
      @comment.destroy
      flash[:success] = 'コメントが削除されました'
    else
      flash[:error] = 'コメントの削除権限がありません'
    end

    redirect_to sake_path(@sake)
  end

  private

  def find_sake
    @sake = Sake.find(params[:sake_id])
  end

  def comment_params
    params.require(:comment).permit(:reply)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.user.name %>:</strong> <%= comment.reply %>
</p>
<p>
  <% if user_signed_in? %>
    <% if current_user.id == comment.user.id %>
      <%= link_to '削除する', sake_comment_path(comment.sake, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
      <td></td>
    <% end %>
  <% else %>
    <td></td>
  <% end %>
</p>

app/views/comments/_form.html.erb
<%= form_for [sake, comment], url: sake_comments_path(sake) do |f| %>
  <div class="field">
    <%= f.label :reply %><br>
    <%= f.text_area :reply %>
  </div>
  <div class="actions">
    <%= f.submit "コメントする"%>
  </div>
<% end %>