config/routes.rb
Rails.application.routes.draw do
  get 'tops/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  post 'guest_sign_in', to: 'application#guest_sign_in'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get 'follows'
      get 'followers'
      get 'like'
    end
  end
  namespace :admin do
    resources :users
  end

  resources :tops, only: [:index]
  root 'tops#index'
  post '/tops/guest_sign_in', to: 'application#guest_sign_in'
  post 'guest_admin_sign_in', to: 'application#guest_admin_sign_in'

  resources :relationships, only: [:create, :destroy]

  resources :labels

  resources :sakes do
    resources :comments
  end
  
  get 'search', to: 'sakes#search'

  resources :favorites, only: [:index, :create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sake.rb
class Sake < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :image

  validates :name, presence: true
  validates :content, presence: true
  validates :place, presence: true
  validates :sweetness, presence: true, inclusion: { in: 0..5 }
  validates :flavor, presence: true, inclusion: { in: 0..5 }
  validates :sour, presence: true, inclusion: { in: 0..5 }
  validates :feeling, presence: true, inclusion: { in: 0..5 }
  validates :rich, presence: true, inclusion: { in: 0..5 }

  def self.ransackable_attributes(auth_object = nil)
    %w[name place]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[sake]
  end
end

app/controllers/sakes_controller.rb
class SakesController < ApplicationController
  before_action :set_sake, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :user_confirmation, only: [:edit, :update, :destroy]

  # GET /sakes
  def index
    @q = Sake.ransack(params[:q])
    @sake = @q.result(distinct: true)
  end

  # GET /sakes/1
  def show
    @favorite = current_user.favorites.find_by(sake_id: @sake.id)
    @comment = Comment.new
  end

  # GET /sakes/new
  def new
    @sake = Sake.new
  end

  # GET /sakes/1/edit
  def edit
  end

  # POST /sakes
  def create
    @sake = current_user.sakes.build(sake_params)

    if @sake.save
      redirect_to @sake, notice: '投稿しました'
    else
      render :new
    end
  end

  # PATCH/PUT /sakes/1
  def update
    if @sake.update(sake_params)
      redirect_to @sake, notice: '投稿を更新しました'
    else
      render :edit
    end
  end

  # DELETE /sakes/1
  def destroy
    @sake.destroy
    redirect_to sakes_url, notice: '投稿を削除しました'
  end

  def search
    @q = Sake.search(search_params)
    @sake = @q.result(distinct: true)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sake
      @sake = Sake.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sake_params
      params.require(:sake).permit(:name, :image, :content, :place, :sweetness, :flavor, :sour, :feeling, :rich, label_ids: [] )
    end

    def search_params
      params.require(:q).permit!
    end

    def user_confirmation
      if current_user.id != @sake.user.id
        redirect_to sakes_path
      end
    end
end

app/helpers/sakes_helper.rb
module SakesHelper
end

app/views/sakes/_form.html.erb
<%= form_with(model: sake, class: "container mt-5") do |form| %>
  <div class="card">
    <div class="card-header">
      新規投稿
    </div>
    <div class="card-body">
      <% if sake.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h5><%= sake.errors.count %>件のエラーにより、この投稿の保存ができませんでした:</h5>

          <ul>
            <% sake.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :日本酒名, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :画像, class: "form-label" %>
        <%= form.file_field :image, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :レビュー, class: "form-label" %>
        <%= form.text_area :content, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :生産地, class: "form-label" %>
        <%= form.text_field :place, class: "form-control" %>
      </div>

      <div class="container">
        <div class="row">
          <div class="col">
            <div class="mb-3">
              <%= form.label :甘さ, class: "form-label" %>
              <%= form.number_field :sweetness, class: "form-control" %>
            </div>
          </div>
          <div class="col">
            <div class="mb-3">
              <%= form.label :香り, class: "form-label" %>
              <%= form.number_field :flavor, class: "form-control" %>
            </div>
          </div>
          <div class="col">
            <div class="mb-3">
              <%= form.label :酸味, class: "form-label" %>
              <%= form.number_field :sour, class: "form-control" %>
            </div>
          </div>
          <div class="col">
            <div class="mb-3">
              <%= form.label :飲みやすさ, class: "form-label" %>
              <%= form.number_field :feeling, class: "form-control" %>
            </div>
          </div>
          <div class="col">
            <div class="mb-3">
              <%= form.label :コク, class: "form-label" %>
              <%= form.number_field :rich, class: "form-control" %>
            </div>
          </div>
        </div>
      </div>
      <div class="mb-3">
        <% Label.all.each do |label| %>
          <% if action_name == 'new' || action_name == 'create' %>
            <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false, id: "label-#{label.id}" }, label[:id], "" %>
            <label for="label-<%= label.id %>"><%= label.feature %></label>
          <% elsif action_name == 'edit' || action_name == 'update' %>
            <%= form.check_box :label_ids, { multiple: true, checked: @sake.label_ids.include?(label.id), disabled: label[:disabled], include_hidden: false, id: "label-#{label.id}" }, label[:id], "" %>
            <label for="label-<%= label.id %>"><%= label.feature %></label>
          <% end %>
        <% end %>
      </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success'%>
  </div>
<% end %>

app/views/sakes/_search.html.erb
<%= search_form_for @q do |f| %>
  <%= f.search_field :name_or_place_cont, class: 'form-control', placeholder: '検索ワード' %>
  <%= f.submit 'Search' %>
<% end %>

app/views/sakes/edit.html.erb
<h1>編集画面</h1>

<%= render 'form', sake: @sake %>

<%= link_to '詳細を見る', @sake ,class: 'btn btn-success text-white'%> |
<%= link_to '一覧画面', sakes_path ,class: 'btn btn-success text-white'%>

app/views/sakes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container mt-5">
<h1>日本酒投稿一覧</h1>
  <div class="row">
    <div class="col-md-8 mx-auto">
      <%= search_form_for @q, url: sakes_path, method: :get, class: "form-inline" do |f| %>
        <div class="input-group w-100 mb-4">
          <%= f.search_field :name_or_place_cont, class: 'form-control', placeholder: '日本酒名か生産地（都道府県まで）' %>
          <div class="input-group-append">
            <%= f.submit '検索', class: "btn btn-success" %>
          </div>
        </div>
      <% end %>
      <% @sake.each do |sake| %>
        <div class="card mb-4">
          <div class="card-header">
            <div class="d-flex justify-content-between">
              <div>
                <strong><%= link_to sake.user.name, user_path(sake.user.id) %></strong>
              </div>
              <div>
                日本酒名: <%= sake.name %>
              </div>
            </div>
          </div>
          <div class="row no-gutters">
            <div class="col-md-4">
              <% if sake.image.attached? %>
                <%= image_tag sake.image, class: "card-img", alt: "#{sake.name}の画像" %>
              <% else %>
                <%= image_tag "no_image.png", class: "card-img", alt: "No Image" %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <p class="card-text">レビュー: <%= sake.content %></p>
                <p class="card-text">生産地: <%= sake.place %></p>
                <p>
                <div class="row">
                  <div class="col">
                    <p class="card-text">甘さ: <%= sake.sweetness %></p>
                  </div>
                  <div class="col">
                    <p class="card-text">香り: <%= sake.flavor %></p>
                  </div>
                  <div class="col">
                    <p class="card-text">酸味: <%= sake.sour %></p>
                  </div>
                  <div class="col">
                    <p class="card-text">飲みやすさ: <%= sake.feeling %></p>
                  </div>
                  <div class="col">
                    <p class="card-text">コク: <%= sake.rich %></p>
                  </div>
                </div>
                </p>
                <p class="card-text">
                  タグ:
                  <% sake.labelings.each do |labeling| %>
                  <span class="badge bg-secondary me-2">
                  <%= labeling.label.feature %>
                  </span>
                  <% end %>
                </p>
                <p class="card-text">お気に入り件数: <%= sake.favorites.count %></p>
                <div>
                <% if user_signed_in? %>
                  <% if current_user.id == sake.user.id %>
                    <%= link_to '詳細を見る', sake %></td>
                    <%= link_to '編集する', edit_sake_path(sake) %></td>
                    <%= link_to '削除する', sake, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <% else %>
                    <td><%= link_to '詳細を見る', sake %></td>
                  <% end %>
                <% else %>
                  <td></td>
                <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12 text-center mt-5">
      <%= link_to '新規投稿', new_sake_path, class: "btn btn-success text-white" %>
    </div>
  </div>
</div>

app/views/sakes/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', sake: @sake %>

<%= link_to '戻る', sakes_path, class: 'btn btn-success' %>

app/views/sakes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <div class="card">
        <div class="card-header">
          <h5 class="mb-0"><strong>日本酒名:</strong> <%= @sake.name %></h5>
        </div>
        <div class="card-body">
          <% if @sake.image.attached? %>
            <div class="text-center mb-4">
              <%= image_tag @sake.image.variant(resize: "300x300"), class: "rounded" %>
            </div>
          <% end %>
          <p><strong>レビュー:</strong> <%= @sake.content %></p>
          <p><strong>生産地:</strong> <%= @sake.place %></p>
          <p>
            タグ:
            <% @sake.labelings.each do |labeling| %>
            <span class="badge bg-secondary me-2">
            <%= labeling.label.feature %>
            </span>
            <% end %>
          </p>
          <div style="width: 400px; height:400px;" class="mx-auto">
            <canvas id="myChart" ></canvas>
          </div>
          <p><strong>お気に入り:</strong> <%= @sake.favorites.count %></p>
          <div class="d-flex justify-content-between mt-3">
            <% unless @sake.user_id == current_user.id %>
              <% if @favorite.present? %>
                <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger text-white' %>
              <% else %>
                <%= link_to 'お気に入りする', favorites_path(sake_id: @sake.id), method: :post, class: 'btn btn-success text-white' %>
              <% end %>
            <% end %>
            <% if current_user.id == @sake.user.id %>
              <%= link_to '編集する', edit_sake_path(@sake), class: 'btn btn-success text-white' %> 
              <%= link_to '戻る', sakes_path, class: 'btn btn-success text-white' %>
            <% else %>
              <%= link_to '戻る', sakes_path, class: 'btn btn-success text-white' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'radar',
    data: {
      labels: ['甘味', '香り', '酸味', '飲みやすさ', 'コク'],
      datasets: [{
        label: '評価',
        data: [<%= @sake.sweetness %>, <%= @sake.flavor %>, <%= @sake.sour %>, <%= @sake.feeling %>, <%= @sake.rich %>],
        borderWidth: 2
      }]
    },
    options: {
      scale: {
        r: {
          beginAtZero: true,
          min: 0, 
          max: 5, 
          stepSize: 0.5 
        }
      }
    }
  });
</script>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 mx-auto">
      <div class="card">
        <div class="card-header">
          <h3>コメント</h3>
        </div>
        <div class="card-body">
          <%= render @sake.comments %>
        </div>
      </div>

      <div class="card mt-4">
        <div class="card-header">
          <h3>コメントを追加</h3>
        </div>
        <div class="card-body">
        <% if flash[:alert] %>
          <div class="alert alert-danger">
            <%= flash[:alert] %>
          </div>
        <% end %>
          <%= render 'comments/form', sake: @sake, comment: @comment %>
        </div>
      </div>
    </div>
  </div>
</div>