config/routes.rb
Rails.application.routes.draw do
  get 'tops/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  post 'guest_sign_in', to: 'application#guest_sign_in'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get 'follows'
      get 'followers'
      get 'like'
    end
  end
  namespace :admin do
    resources :users
  end

  resources :tops, only: [:index]
  root 'tops#index'
  post '/tops/guest_sign_in', to: 'application#guest_sign_in'
  post 'guest_admin_sign_in', to: 'application#guest_admin_sign_in'

  resources :relationships, only: [:create, :destroy]

  resources :labels

  resources :sakes do
    resources :comments
  end
  
  get 'search', to: 'sakes#search'

  resources :favorites, only: [:index, :create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sakes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_sakes, through: :favorites, source: :sake
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followed, through: :passive_relationships, source: :follower
  has_one_attached :image
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.guest_admin
    find_or_create_by!(email: 'admin_guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.admin = true
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  #DELETE /resource/sign_out
    #def destroy
      #super
    #end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.id == current_user.id
      @user.update(user_params)
    end
    redirect_to @user
  end

  def follows
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end

  def like
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :recommend, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "フォローを解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container mt-5">
  <h1 class="mb-4">プロフィール編集</h1>

  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @user, local: true) do |f| %>  
    <div class="form-group">
      <%= f.label :名前, class: "control-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :メールアドレス, class: "control-label" %>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :オススメの一本, class: "control-label" %>
      <%= f.text_field :recommend, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :自己紹介, class: "control-label" %>
      <%= f.text_field :introduction, class: "form-control" %>
    </div>

    <%= f.submit "更新", class: "btn btn-success" %>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="container mt-5">
<h1 class="mb-4">フォロワー一覧</h1>
  <div class="row">
    <% @user.followed.each do |user| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-header">
            <h5 class="card-title"><%= link_to user.name, user_path(user) %></h5>
          </div>
          <div class="card-body">
            <p class="card-title"><%= user.introduction %><p>
            <div class="d-flex justify-content-between">
              <%= render 'follow_form', user: user %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container mt-5">
<h1 class="mb-4">フォロー一覧</h1>
  <div class="row">
    <% @user.following.each do |user| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-header">
            <h5 class="card-title"><%= link_to user.name, user_path(user) %></h5>
          </div>
          <div class="card-body">
            <p class="card-title"><%= user.introduction %><p>
            <div class="d-flex justify-content-between">
              <%= render 'follow_form', user: user %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4">ユーザー一覧</h1>
  <h2 class="mb-3">ユーザー</h2>
  <div class="row">
    <% new_users = @users.reject { |user| user.id == current_user.id } %>
    <% new_users.each_slice(3) do |user_slice| %>
      <div class="row">
        <% user_slice.each do |user| %>
          <div class="col-md-4">
            <div class="card mb-4">
              <div class="card-header">
                <strong><%= link_to user.name, user_path(user) %></strong>
                <%#= user.email %>
              </div>
              <div class="card-body">
                <p class="card-title"><%= user.introduction %><p>
                <div>
                  <%= render 'follow_form', user: user %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/like.html.erb
<p id="notice"><%= notice %></p>
<div class="container mt-5">
<h1><%= "#{@user.name}のお気に入り一覧" %></h1>
  <div class="row">
    <div class="col-md-8 mx-auto">
      <% @user.favorite_sakes.each do |sake| %>
        <div class="card mb-4">
          <div class="card-header">
            <div class="d-flex justify-content-between">
              <div>
                <strong><%= link_to sake.user.name, user_path(sake.user.id) %></strong>
              </div>
              <div>
                日本酒名: <%= sake.name %>
              </div>
            </div>
          </div>
          <div class="row no-gutters">
            <div class="col-md-4">
              <% if sake.image.attached? %>
                <%= image_tag sake.image, class: "card-img", alt: "#{sake.name}の画像" %>
              <% else %>
                <%= image_tag "no_image.png", class: "card-img", alt: "No Image" %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <p class="card-text">レビュー内容: <%= sake.content %></p>
                <p class="card-text">生産地: <%= sake.place %></p>
                <div class="row">
                  <div class="col">
                    <p class="card-text">甘さ: <%= sake.sweetness %></p>
                  </div>
                  <div class="col">
                    <p class="card-text">香り: <%= sake.flavor %></p>
                  </div>
                  <div class="col">
                    <p class="card-text">酸味: <%= sake.sour %></p>
                  </div>
                  <div class="col">
                    <p class="card-text">飲みやすさ: <%= sake.feeling %></p>
                  </div>
                  <div class="col">
                    <p class="card-text">コク: <%= sake.rich %></p>
                  </div>
                </div>
                <div class="col">
                  <p class="card-text">
                    タグ:
                    <% sake.labelings.each do |labeling| %>
                      <%= labeling.label.feature %><br>
                    <% end %>
                  </p>
                </div>
                <div>
                  <% if user_signed_in? %>
                    <% if current_user.id == sake.user.id %>
                      <%= link_to '詳細を見る', sake %></td>
                      <%= link_to '編集する', edit_sake_path(sake) %></td>
                      <%= link_to '削除する', sake, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <% else %>
                      <td><%= link_to '詳細を見る', sake %></td>
                    <% end %>
                  <% else %>
                    <td></td>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
    <div class="d-flex flex-wrap justify-content-center mb-3">
      <%= link_to '投稿一覧', sakes_path, class: 'btn btn-success text-white' %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <h1 class="mb-4">ユーザー情報</h1>

  <table class="table table-hover">
    <tbody>
      <tr>
        <th>ユーザー</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th>オススメの一本</th>
        <td><%= @user.recommend %></td>
      </tr>
      <tr>
        <th>自己紹介</th>
        <td><%= @user.introduction %></td>
      </tr>

      <tr>
        <th><%= link_to "フォロー", follows_user_path %></th>
        <td><%= @user.active_relationships.count%></td>
      </tr>

      <tr>
        <th><%= link_to "フォロワー", followers_user_path %></th>
        <td><%= @user.passive_relationships.count%></td>
      </tr>
    </tbody>
  </table>
  <div class="mb-3">
    <table class="table table-hover">
      <thead class="thead-default">
        <tr>
          <th>日本酒</th>
          <th>コメント</th>
          <th>生産地</th>
        </tr>
      </thead>
      <tbody>
        <% @user.sakes.each do |t| %>
          <tr>
            <td><%= link_to t.name, sake_path(t)%></td>
            <td><%= t.content %></td>
            <td><%= t.place %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="d-flex flex-wrap justify-content-between mb-3">
    <%= link_to 'お気に入り一覧', like_user_path, class: 'btn btn-success text-white' %>
    <% if current_user.id == @user.id %>
      <%= link_to '編集', edit_user_path(@user), class: 'btn btn-success text-white' %>
    <% end %>
    <% if current_user == @user && current_user.admin? %>
      <%= link_to "管理者ページ", admin_users_path, class: 'btn btn-success text-white' %>
    <% end %>
    <%= link_to '投稿一覧', sakes_path, class: 'btn btn-success text-white' %>
  </div>
</div>